#!/bin/bash

file_name="renpaste"
bin_path="$HOME/.local/bin"
icon_path="$HOME/.local/share/icons/hicolor/48x48/apps"
desk_path="$HOME/.local/share/applications"

base_url="https://raw.githubusercontent.com/aintnodev/renpaste/main"
bin_url="$base_url/$file_name"

while getopts "uih" opt; do
  case $opt in
  u)
    rm -f "$bin_path/$file_name"
    rm -f "$icon_path/$file_name.png"
    rm -f "$desk_path/$file_name.desktop"
    echo "Uninstalled $file_name from $bin_path"
    ;;
  i)
    mkdir -p "$bin_path" "$icon_path" "$desk_path"

    curl -L -o "$bin_path/$file_name" "$bin_url"
    curl -L -o "$icon_path/$file_name.png" "$bin_url.png"
    curl -L -o "$desk_path/$file_name.desktop" "$bin_url.desktop"

    chmod +x "$bin_path/$file_name"

    echo "Installed $file_name to $bin_path"
    ;;
  h)
    echo "Usage: $file_name -i (install) | -u (uninstall)"
    ;;
  *)
    echo "Error: use $file_name -h for usage"
    exit 1
    ;;
  esac
done
