#!/bin/bash

file_name_bin="renpaste"
file_name_icon="renpaste.png"
file_name_desk="renpaste.desktop"

bin_path="$HOME/.local/bin"
icon_path="$HOME/.local/share/"
desk_path="$HOME/.local/share/applications"

bin_url="https://github.com/aintnodev/renpy-saves/blob/main/$file_name"
icon_url="https://github.com/aintnodev/renpy-saves/blob/main/$file_name"
desk_url="https://github.com/aintnodev/renpy-saves/blob/main/$file_name"

while getopts "ui" opt; do
  case $opt in
  u)
    rm -f "$bin_path/$file_name_bin"
    rm -f "$icon_path/$file_name_icon"
    rm -f "$desk_path/$file_name_desk"
    echo "Uninstalled $file_name from $bin_path"
    ;;
  i)
    mkdir -p "$bin_path" "$icon_path" "$desk_path"

    curl -L -o "$bin_path/$file_name_bin" "$bin_url"
    curl -L -o "$icon_path/$file_name_icon" "$bin_url"
    curl -L -o "$desk_path/$file_name_desk" "$bin_url"

    chmod +x "$bin_path/$file_name_bin"

    echo "Installed $file_name_bin to $bin_path"
    ;;
  *)
    echo "Usage: setup -i | -u"
    ;;
  esac
done
